tunnel: 72e0dd9e-956d-4f64-8863-d7290463856f
credentials-file: /home/bot/.config/tesseract/tesseract-web-tunnel-credentials.json

ingress:
  - hostname: tesseract-hooks.achan.bot
    path: ^/api/slack/events$
    service: https://127.0.0.1:6100
    originRequest:
      originServerName: tesseract-web.tars.achan.bot

  - hostname: tesseract-hooks.achan.bot
    path: ^/api/deploy$
    service: https://127.0.0.1:6100
    originRequest:
      originServerName: tesseract-web.tars.achan.bot

  - hostname: tesseract-hooks.achan.bot
    path: ^/api/live_activities(?:/(?:start|progress|stop))?$
    service: https://127.0.0.1:6100
    originRequest:
      originServerName: tesseract-web.tars.achan.bot

  - service: http_status:404
