tunnel: 23ed10b2-83d7-49cf-a279-118cc039d2aa
credentials-file: /home/bot/.config/tesseract/tesseract-web-tunnel-credentials.json

ingress:
  - hostname: tesseract-hooks.achan.bot
    path: ^/api/slack/events$
    service: https://127.0.0.1:6100
    originRequest:
      originServerName: tesseract-web.tars.achan.bot

  - hostname: tesseract-hooks.achan.bot
    path: ^/api/deploy$
    service: https://127.0.0.1:6100
    originRequest:
      originServerName: tesseract-web.tars.achan.bot

  - service: http_status:404
